```{r}
library(tidyverse)

# data location
url <- "http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

# import
census <- read_csv(url,
                   col_names = c("age", 
                                 "workclass", 
                                 "fnlwgt", 
                                 "education",
                                 "education_1",
                                 "marital_status",
                                 "occupation",
                                 "relationship",
                                 "race",
                                 "sex",
                                 "capital_gain",
                                 "capital_loss",
                                 "hours_per_week",
                                 "native_country",
                                 "income")) %>%
  mutate(income = factor(income)) %>%
  select(-fnlwgt, -education_1)

census %>% head(4)
```


```{r}
# inspect repsonse
census %>% pull(income) %>% str()
```

Step 1: resample the data
```{r}
# resample data
census_boot <- census %>%
  sample_n(size = 200, replace = T)
```

Step 2: select predictors at random
```{r}
# retrieve column names
possible_predictors <- census %>% 
  select(-income) %>%
  colnames()

# grab 2 columns at random
predictors <- sample(possible_predictors,
                     size = 2, 
                     replace = F)

# select these columns from the bootstrap sample
train <- census_boot %>% 
  select(c(income, any_of(predictors)))
train
```

```{r}
# comment out -- don't overwrite your bootstrap sample!
census_boot <- census %>% 
  sample_n(size = 200, replace = T)

# for continuous variables
census_boot %>%
  ggplot(aes(x = age, # replace with predictor name 
             y = income)) +
  geom_jitter(height = 0.1) +
  geom_vline(xintercept = 35) # adjust cutoff
```
```{r}
census_boot %>%
  ggplot(aes(x = hours_per_week, # replace with predictor name
           y = ..density..)) +
  geom_density(aes(color = income, fill = income),
               alpha = 0.5) +
  geom_vline(xintercept = 35) # adjust cutoff
```
```{r}
# for categorical variables
census_boot %>%
  group_by(education, income) %>%
  count() %>%
  spread(income, n) %>%
  mutate_all(~ replace_na(.x, 0)) %>%
  mutate(high.inc = `<=50K` > `>50K`)
```
```{r}
# pick out categories that are majority high income
highinc_categories <- census_boot %>%
  group_by(education, # replace with predictor name
           income) %>%
  count() %>%
  spread(income, n) %>%
  mutate_all(~ replace_na(.x, 0)) %>%
  mutate(high.inc = `<=50K` > `>50K`) %>%
  filter(high.inc == T) %>%
  pull(education) # replace with predictor name
```



